"""add payments table

Revision ID: a680b5d9499c
Revises: db77433f5b64
Create Date: 2026-05-18 22:42:33.251825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a680b5d9499c'
down_revision = 'db77433f5b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_no', sa.String(length=20), nullable=False),
    sa.Column('ecpay_trade_no', sa.String(length=50), nullable=True),
    sa.Column('payment_type', sa.Enum('flash', 'course', name='paymenttype'), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payer_name', sa.String(length=100), nullable=False),
    sa.Column('payer_email', sa.String(length=120), nullable=False),
    sa.Column('payer_phone', sa.String(length=30), nullable=True),
    sa.Column('payer_note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'paid', 'failed', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('ecpay_payment_method', sa.String(length=50), nullable=True),
    sa.Column('ecpay_raw_response', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_payer_email'), ['payer_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_type'), ['payment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_trade_no'), ['trade_no'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_trade_no'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_type'))
        batch_op.drop_index(batch_op.f('ix_payments_payer_email'))

    op.drop_table('payments')
    # ### end Alembic commands ###
