"""add flash_designs table

Revision ID: db77433f5b64
Revises: 
Create Date: 2026-05-18 22:12:31.261243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db77433f5b64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flash_designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('thumb_url', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('placement', sa.String(length=100), nullable=True),
    sa.Column('size_note', sa.String(length=100), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_claimed', sa.Boolean(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flash_designs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flash_designs_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flash_designs_is_claimed'), ['is_claimed'], unique=False)
        batch_op.create_index(batch_op.f('ix_flash_designs_slug'), ['slug'], unique=True)

    op.create_table('flash_styles',
    sa.Column('flash_id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flash_id'], ['flash_designs.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ),
    sa.PrimaryKeyConstraint('flash_id', 'style_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flash_styles')
    with op.batch_alter_table('flash_designs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flash_designs_slug'))
        batch_op.drop_index(batch_op.f('ix_flash_designs_is_claimed'))
        batch_op.drop_index(batch_op.f('ix_flash_designs_artist_id'))

    op.drop_table('flash_designs')
    # ### end Alembic commands ###
